import type { Metadata } from "next";
import { Cormorant_Garamond, DM_Sans, Inter } from "next/font/google";
import Frame from "./components/common/Frame";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import Preloader from "./components/common/Preloader";
import Pagetransition from "./components/common/Pagetransition";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${inter.variable} ${cormorantGaramond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#f8f8f8]">
        <Preloader />
        <Pagetransition>
          <div className="relative min-h-screen bg-[#f8f8f8] flex items-center justify-center p-3 md:p-5">
            <Header position="fixed" />
            <Frame id="site-frame" contentClassName="p-0">
              {children}
              <Footer />
            </Frame>
          </div>
        </Pagetransition>
      </body>
    </html>
  );
}
